// part1b.js — Part I: audit items 9–16
module.exports = function build(H) {
  const { h2, p, bullets } = H;
  const out = [];

  // ── 9 ──
  out.push(h2("9. Analytics Gaps"));
  out.push(p("The signal engine is genuinely multi-factor and transparent, but analytics around it are thin. Portfolio intelligence (Section 15) is absent: there is no asset-allocation view, no sector or long/short exposure breakdown, no concentration warning for overlapping positions, no correlation matrix, no portfolio volatility or drawdown series, and no scenario analysis. The regime engine exists and demonstrably labels the briefing RISK_ON or RISK_OFF, but it publishes a state without the explanation Section 13 requires (why is this regime active?), and its vocabulary - risk-on, risk-off, mixed - does not yet include the volatility, momentum, mean-reversion, event-driven, and liquidity-stress states the mandate lists."));
  out.push(p("Factor coverage also lags the target list. ATR is used for stop construction but not surfaced as a scored contribution; liquidity, spread, relative strength, and portfolio-context factors (exposure and correlation) are absent from the factor set entirely. Signal performance tracking (Section 24) has the right seed - trades and a win-rate field exist - but there is no signal-level outcome ledger recording every generated signal with entry, stop, target, realized R-multiple, regime, and catalyst, which is what allows the product to measure whether its own engine is useful and to refuse cherry-picking. Finally, no beginner/advanced presentation split exists (Section 54): every user currently sees the full professional density."));

  // ── 10 ──
  out.push(h2("10. SENTINEL Gaps"));
  out.push(p("The mode architecture matches the spec's intent closely - SIGNAL_ONLY, SEMI-AUTO, and FULL AUTO map cleanly onto Observe, Approve, and Delegate - and the hard-limit sliders (risk per trade, max positions, daily-loss breaker, minimum confidence) are the right vocabulary. The gaps are in enforcement completeness and per-user binding. The approval flow has an expiry (600 seconds, configurable 30 to 600), but there is no evidence approvals are single-use tokens bound to one user and one trade; Section 16 requires user-specific, trade-specific, single-use, time-limited, audited approvals, and three of those five properties are unverifiable in the current singleton world."));
  out.push(p("Missing risk controls relative to Sections 4 and 16 include: a weekly loss cap, a maximum daily trades count, a correlated-exposure cap, minimum liquidity and spread requirements, volatility restrictions, and news/event restrictions (for example, blocking entries minutes before earnings). The safety-state machine of Section 17 is represented only by a haltedReason field; states such as WAITING_FOR_APPROVAL, RISK_LOCKED, BROKER_DISCONNECTED, DATA_UNAVAILABLE, NEWS_PROVIDER_UNAVAILABLE, and SYSTEM_DEGRADED need to exist as first-class, UI-explained states. And the emergency stop of Section 18 does not exist as a dedicated, always-visible control with cancel-pending semantics - the current enable/disable toggle is a mode switch, not a kill switch."));

  // ── 11 ──
  out.push(h2("11. News and Catalyst Gaps"));
  out.push(p("There is no news ingestion of any kind. No news provider is called, no catalyst entity exists, and the briefing's narratives are composed from price, volume, and sector data alone. This produces exactly the failure the mandate anticipated: the avoid list justified MDB with an earnings-disappointment narrative and NVDA with an AI-optimism narrative, but no headline, source, URL, or timestamp supports either claim - the model inferred stories from price action. Section 11 requires every catalyst to carry headline, source, timestamp, URL, category, sentiment, relevance, strength, and affected tickers, and forbids both fabrication and the display of No news unless absence was actually verified."));
  out.push(p("The cost warning in Section 11's addendum also applies in full: a news feed is the first feature on the roadmap with real recurring per-request cost, so the provider must be priced against free-tier limits at 100, 1,000, and 10,000 users before any UI is built. The audit's recommendation (detailed in item 21 and Part IV) is a free-tier-first integration behind the NewsProvider interface with server-side caching and deduplication, deferring paid feeds until users demonstrate the value."));

  // ── 12 ──
  out.push(h2("12. Crypto Gaps"));
  out.push(p("Crypto is entirely absent: the universe is equities and ETFs (including leveraged ETFs such as SOXL and TQQQ), the session model assumes an equity clock, and no 24/7 market handling exists anywhere in the observed behavior. This is acceptable for now - crypto was consciously deferred - but the audit flags the Section 4 addendum requirement early because it is architectural, not cosmetic: when crypto returns, SENTINEL's risk engine must apply asset-class-specific volatility bands, position sizing, ATR-termed stop distances, and daily-loss circuit breakers rather than reusing equity-calibrated defaults. A 24/7 market with higher realized volatility will otherwise either trip equity-tuned breakers constantly or, worse, undersize the controls relative to how fast crypto moves."));
  out.push(p("The practical consequences for the data model are worth stating now so Phase 1 does not paint the corner: SymbolMeta needs an assetClass field, the regime engine needs per-asset-class regimes, the session scheduler needs an always-open market mode, and the risk gate needs a calibration table keyed by asset class. None of this is expensive to include in the Phase 1 schema; all of it is annoying to retrofit after equity assumptions harden."));

  // ── 13 ──
  out.push(h2("13. Trading and Execution Gaps"));
  out.push(p("Execution is currently one internal paper engine behind ad-hoc endpoints, with no ExecutionProvider interface. The Section 19 abstraction - QuantEdgePaperProvider beside AlpacaPaperProvider, with an eye toward a future live provider - does not exist, and Alpaca integration is absent. Fill realism is the second cluster (item 2): slippage, spread, latency, partial fills, rejections, and gap behavior are all unmodeled. Third, order plumbing lacks the durability the mandate demands: no idempotency keys (Section 59), no explicit order lifecycle states (pending, partial, filled, cancelled, rejected), and no broker-connection health tracking that could drive a BROKER_DISCONNECTED safety state."));
  out.push(p("The approval-to-execution path exists in skeleton (pending approvals with expiry, approve/reject actions) but needs the Section 16 hardening: single-use tokens, user binding, audited decisions, and expiry that logs rather than executes. Finally, the Section 19 addendum instruction to design for a live-money future without building one should be honored explicitly: the ExecutionProvider interface and user-facing copy should be worded so a live broker could slot in later, while the audit records here - as the addendum requires - that enabling real-money execution would introduce broker-dealer, pattern-day-trader, and KYC obligations that paper trading does not carry, so that decision gets made deliberately."));

  // ── 14 ──
  out.push(h2("14. Backtesting Gaps"));
  out.push(p("There is no backtesting engine, no walk-forward validation, and no Strategy Lab. The bot's trade log is a forward paper record, not a backtest, and the audit found no historical simulation code path in the bundle. Section 21's metric suite (total return, CAGR, maximum drawdown, Sharpe, Sortino, win rate, average win and loss, largest win and loss, profit factor, expectancy, trade count, exposure, and benchmark comparison) and its bias controls (look-ahead, future-data leakage, survivorship bias, unrealistic fills) are therefore greenfield work, scheduled in Phase 3."));
  out.push(p("Two design notes from the audit are worth carrying into Phase 3. First, the signal engine already persists factor-level context; a backtest that replays the same factor computations over historical candles shares code with live scoring, which prevents the two engines from drifting apart. Second, the fill model built for realistic paper execution (item 13) must be the same fill model used inside the backtester, or paper results and backtest results will disagree in ways users will eventually notice. Walk-forward support (Section 22) should be designed in from the start - train and out-of-sample windows with an explicit explanation when out-of-sample performance diverges - rather than bolted on after a single-period backtester exists."));

  // ── 15 ──
  out.push(h2("15. Notification Gaps"));
  out.push(p("Notifications do not exist in any channel: no web push, no email, no mobile push, no in-app notification center, no preference management, no quiet hours, and no delivery state tracking. The event sources the mandate lists in Section 25 - new signals, high-confidence opportunities, approval requests, executions, stops and targets, risk limits, broker disconnection, major catalysts, system degradation, and security events - all already originate inside the bot and analytics logic, so the work is transport and preference machinery, not new intelligence."));
  out.push(p("The sequencing addendum to Section 25 is binding: web push and email ship first because they are deliverable from the current web app, and mobile push activates only once Phase 9 produces installable shells - a web-only build cannot deliver native push to a phone with no app. The delivery state machine (queued, sent, delivered, opened, failed, retry) and the honesty rule that the system never pretends a notification was delivered both belong to Phase 5 alongside the notification center UI."));

  // ── 16 ──
  out.push(h2("16. Mobile Gaps"));
  out.push(p("The current UI is a desktop terminal that shrinks; the audit found no mobile-specific navigation pattern, no bottom tab bar of the Section 36 shape (Home, Markets, Signals, Portfolio, More), and no PWA manifest or service worker in the served assets. The approval flow - the single most important mobile interaction in the product - has not been designed for one-or-two-tap completion on a phone, and chart interactions (pinch zoom, crosshair dragging) are unverified on touch devices."));
  out.push(p("The recommendation, elaborated in artifact H, is responsive web plus PWA first: the same backend brain with a dedicated mobile layout, installable to a home screen, shipping in Phase 8/9; native or wrapped shells follow only when store presence is actually needed, at which point the Section 35 addendum's in-app-purchase requirements and the Section 25 push sequencing both activate. Designing the component library now with mobile breakpoints in mind costs little; retrofitting it after the desktop layout hardens costs a Phase."));

  return out;
};
